[{"id":705424290,"node_id":"R_kgDOKgvrog","name":"CVE-2019-9053-Python3","full_name":"Doc0x1/CVE-2019-9053-Python3","private":false,"owner":{"login":"Doc0x1","id":19937034,"node_id":"MDQ6VXNlcjE5OTM3MDM0","avatar_url":"https://avatars.githubusercontent.com/u/19937034?v=4","url":"https://api.github.com/users/Doc0x1","html_url":"https://github.com/Doc0x1","type":"User","site_admin":false},"html_url":"https://github.com/Doc0x1/CVE-2019-9053-Python3","description":"Python3 version of the Python2 exploit for CVE-2019-9053","fork":false,"url":"https://api.github.com/repos/Doc0x1/CVE-2019-9053-Python3","created_at":"2023-10-16T01:09:13Z","updated_at":"2023-10-16T01:32:31Z","pushed_at":"2023-10-16T01:30:34Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":["cve","cve-2019-9053","exploit","python","python3","ubuntu1804"],"visibility":"public","forks":0,"watchers":0,"default_branch":"master","score":1}]